# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nwestimator <- function(inputval, xvals, yvals, h) {
    .Call('NOIS_nwestimator', PACKAGE = 'NOIS', inputval, xvals, yvals, h)
}

nwvector <- function(x, y, h) {
    .Call('NOIS_nwvector', PACKAGE = 'NOIS', x, y, h)
}

LOOCV <- function(x, y, h, samp_quant) {
    .Call('NOIS_LOOCV', PACKAGE = 'NOIS', x, y, h, samp_quant)
}

biasnwestimator <- function(inputval, xvals, yvals, h, inputnw, nwvals, shift_sq = FALSE) {
    .Call('NOIS_biasnwestimator', PACKAGE = 'NOIS', inputval, xvals, yvals, h, inputnw, nwvals, shift_sq)
}

biasnwvector <- function(x, y, nwvals, h) {
    .Call('NOIS_biasnwvector', PACKAGE = 'NOIS', x, y, nwvals, h)
}

top_index <- function(x, n) {
    .Call('NOIS_top_index', PACKAGE = 'NOIS', x, n)
}

quantile_thresh <- function(x, thresh_val) {
    .Call('NOIS_quantile_thresh', PACKAGE = 'NOIS', x, thresh_val)
}

NOIS_loop <- function(xx, yy, first_h, local_q, tol, maxit) {
    .Call('NOIS_NOIS_loop', PACKAGE = 'NOIS', xx, yy, first_h, local_q, tol, maxit)
}

